name: API Tests - HENI News

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  heni-news-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run API Tests
        run: mvn clean test -pl :analytics
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-reports
          path: target/cucumber-html-reports/
